spring.application.name=reactPractise

spring.datasource.url = jdbc:postgresql://localhost:1234/reactProduct
spring.datasource.username = postgres
spring.datasource.password = root
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.defer-datasource-initialization = true
